apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: recipe-manager
  labels:
    app.kubernetes.io/name: recipe-manager-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: recipe-manager-app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: recipe_manager_user
  SPRING_DATASOURCE_PASSWORD: recipe_manager_password